services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
volumes:
  redis_data:
    driver: local
