services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # server:
  #   build:
  #     context: ./
  #   ports:
  #     - "8000:8000"
  #   env_file: ./.env
  #   restart: unless-stopped
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0

volumes:
  redis_data:
